import { useState, useRef, useEffect } from "react";
import './App.css';

const DEFAULT_ITEMS = [
  { id: 1, name: "Notepad", icon: "C:\\Windows\\System32\\notepad.exe", target: "C:\\Windows\\System32\\notepad.exe", type: "app" },
  { id: 2, name: "Downloads", icon: "", target: "C:\\Users\\%USERNAME%\\Downloads", type: "folder" },
];

const HOTKEY_OPTIONS = [
  { label: "Win + Z", value: "#z", display: "⊞ Win + Z" },
  { label: "Win + Space", value: "#Space", display: "⊞ Win + Space" },
  { label: "Ctrl + Space", value: "^Space", display: "Ctrl + Space" },
  { label: "Ctrl + Shift + M", value: "^+m", display: "Ctrl + ⇧ + M" },
  { label: "Alt + Space", value: "!Space", display: "Alt + Space" },
  { label: "Win + Q", value: "#q", display: "⊞ Win + Q" },
  { label: "Middle Click", value: "MButton", display: "🖱 Mid Click" },
  { label: "Custom", value: "custom", display: "Custom" },
];

const TYPE_ICONS = {
  app: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect x="2" y="4" width="20" height="16" rx="2" />
      <path d="M2 8h20" />
      <path d="M6 4v4" />
    </svg>
  ),
  folder: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M4 20h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.93a2 2 0 0 1-1.66-.9l-1.22-1.8A2 2 0 0 0 7.53 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </svg>
  ),
  url: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
      <path d="M2 12h20" />
    </svg>
  ),
  separator: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <line x1="4" y1="12" x2="20" y2="12" strokeDasharray="4 4" />
    </svg>
  ),
  submenu: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M4 6h16" />
      <path d="M4 12h8" />
      <path d="M4 18h16" />
      <polyline points="15 9 18 12 15 15" />
    </svg>
  ),
};

const updateItemRec = (items, id, updated) => {
  return items.map(item => {
    if (item.id === id) return { ...item, ...updated };
    if (item.children) return { ...item, children: updateItemRec(item.children, id, updated) };
    return item;
  });
};

const deleteItemRec = (items, id) => {
  return items.filter(i => i.id !== id).map(item => {
    if (item.children) return { ...item, children: deleteItemRec(item.children, id) };
    return item;
  });
};

const addItemRec = (items, parentId, newItem) => {
  if (parentId === null) return [...items, newItem];
  return items.map(item => {
    if (item.id === parentId) {
      return { ...item, children: [...(item.children || []), newItem] };
    }
    if (item.children) {
      return { ...item, children: addItemRec(item.children, parentId, newItem) };
    }
    return item;
  });
};

const moveItemRec = (items, id, dir) => {
  const index = items.findIndex(i => i.id === id);
  if (index !== -1) {
    const newIdx = index + dir;
    if (newIdx < 0 || newIdx >= items.length) return items;
    const copy = [...items];
    [copy[index], copy[newIdx]] = [copy[newIdx], copy[index]];
    return copy;
  }
  return items.map(item => {
    if (item.children) {
      return { ...item, children: moveItemRec(item.children, id, dir) };
    }
    return item;
  });
};

function generateAHK(items, hotkey, customHotkey, menuTitle) {
  const hk = hotkey === "custom" ? customHotkey : hotkey;
  let script = `; ═══════════════════════════════════════════════════════
; Custom Context Menu — Generated by AHK Menu Designer
; AutoHotkey v1.1+
; ═══════════════════════════════════════════════════════
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

; ── Build the menu ──────────────────────────────────────
`;

  let sepCount = 0;
  let subMenuCounter = 0;
  let flatItems = [];

  function processMenu(menuItems, menuName) {
    menuItems.forEach((item) => {
      if (item.type === "separator") {
        sepCount++;
        script += `Menu, ${menuName}, Add  ; separator ${sepCount}\n`;
        return;
      }

      const safeName = item.name.replace(/&/g, "&&") || "Untitled";

      if (item.type === "submenu") {
        subMenuCounter++;
        const subName = `SubMenu${subMenuCounter}`;
        
        if (item.children && item.children.length > 0) {
          processMenu(item.children, subName);
        } else {
          script += `Menu, ${subName}, Add, (Empty), MenuHandler\n`;
          script += `Menu, ${subName}, Disable, (Empty)\n`;
        }
        
        script += `Menu, ${menuName}, Add, ${safeName}, :${subName}\n`;
        if (item.icon && item.icon.trim()) {
          script += `Menu, ${menuName}, Icon, ${safeName}, ${item.icon}\n`;
        }
      } else {
        script += `Menu, ${menuName}, Add, ${safeName}, MenuHandler\n`;
        if (item.icon && item.icon.trim()) {
          script += `Menu, ${menuName}, Icon, ${safeName}, ${item.icon}\n`;
        }
        flatItems.push(item);
      }
    });
  }

  processMenu(items, "QuickMenu");

  script += `
; ── Hotkey ───────────────────────────────────────────────
${hk}::
    Menu, QuickMenu, Show
return

; ── Handler ──────────────────────────────────────────────
MenuHandler:
`;

  const nonSepItems = flatItems.filter((i) => i.type !== "separator");
  nonSepItems.forEach((item, idx) => {
    const safeName = item.name.replace(/&/g, "&&") || "Untitled";
    const condition = idx === 0 ? "if" : "else if";

    if (item.type === "folder") {
      script += `    ${condition} (A_ThisMenuItem = "${safeName}")\n        Run, explorer.exe "${item.target}"\n`;
    } else if (item.type === "url") {
      script += `    ${condition} (A_ThisMenuItem = "${safeName}")\n        Run, ${item.target}\n`;
    } else {
      script += `    ${condition} (A_ThisMenuItem = "${safeName}")\n        Run, "${item.target}"\n`;
    }
  });

  if (nonSepItems.length > 0) {
    script += `return\n`;
  } else {
    script += `    ; No items to handle\nreturn\n`;
  }
  
  return script;
}

function MenuItemRow({ item, onUpdate, onDelete, onMoveUp, onMoveDown, isFirst, isLast, index, depth = 0, onAddChild }) {
  if (item.type === "separator") {
    return (
      <div className="menu-item-row" style={{ alignItems: "center", marginLeft: depth * 24 }}>
        <span className="item-index">{index + 1}</span>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--text-muted)' }}>
          {TYPE_ICONS.separator}
          <span style={{ fontSize: '0.85rem', fontStyle: 'italic' }}>Separator</span>
        </div>
        <div style={{ flex: 1 }} />
        <div className="item-actions" style={{ flexDirection: 'row' }}>
          <button className="action-btn move" onClick={onMoveUp} disabled={isFirst}>▲</button>
          <button className="action-btn move" onClick={onMoveDown} disabled={isLast}>▼</button>
          <button className="action-btn delete" onClick={onDelete}>×</button>
        </div>
      </div>
    );
  }

  return (
    <div style={{ marginLeft: depth * 24, paddingLeft: depth > 0 ? '12px' : '0', borderLeft: depth > 0 ? '2px solid rgba(255,255,255,0.05)' : 'none' }}>
      <div className="menu-item-row" style={{ marginBottom: item.type === "submenu" ? '0' : '0.75rem' }}>
        <span className="item-index">{index + 1}</span>
        <div className="item-content">
          <div className="item-row">
            <div className="type-toggle">
              {["app", "folder", "url", "submenu"].map(t => (
                <button
                  key={t}
                  className={`type-btn ${item.type === t ? 'active' : ''}`}
                  onClick={() => onUpdate({ ...item, type: t })}
                  title={t.charAt(0).toUpperCase() + t.slice(1)}
                >
                  {TYPE_ICONS[t]}
                </button>
              ))}
            </div>
            <input
              className="input-field"
              value={item.name}
              onChange={(e) => onUpdate({ ...item, name: e.target.value })}
              placeholder={item.type === "submenu" ? "Submenu Label" : "Menu Label"}
              style={{ fontSize: '0.875rem', fontFamily: 'Inter, sans-serif' }}
            />
          </div>
          
          {item.type !== "submenu" && (
            <div className="item-row">
              <div className="input-group">
                <span className="input-label" style={{ background: '#19191c' }}>
                  {item.type === "folder" ? "Folder Path" : item.type === "url" ? "URL" : "App / Exe Path"}
                </span>
                <input
                  className="input-field"
                  value={item.target}
                  onChange={(e) => onUpdate({ ...item, target: e.target.value })}
                  placeholder={item.type === "folder" ? "C:\\Users\\..." : item.type === "url" ? "https://..." : "C:\\Program Files\\..."}
                />
              </div>
              <div className="input-group" style={{ flex: 0.6 }}>
                <span className="input-label" style={{ background: '#19191c' }}>Icon (optional)</span>
                <input
                  className="input-field"
                  value={item.icon}
                  onChange={(e) => onUpdate({ ...item, icon: e.target.value })}
                  placeholder=".exe, .ico, .dll path"
                />
              </div>
            </div>
          )}
          {item.type === "submenu" && (
            <div className="item-row" style={{ marginTop: '0.5rem', marginBottom: '0.5rem' }}>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button className="add-btn" onClick={() => onAddChild(item.id, "app")} style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem' }}>+ App</button>
                  <button className="add-btn" onClick={() => onAddChild(item.id, "folder")} style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem' }}>+ Folder</button>
                  <button className="add-btn" onClick={() => onAddChild(item.id, "url")} style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem' }}>+ URL</button>
                  <button className="add-btn muted" onClick={() => onAddChild(item.id, "separator")} style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem' }}>— Sep</button>
                </div>
            </div>
          )}
        </div>
        <div className="item-actions">
          <button className="action-btn move" onClick={onMoveUp} disabled={isFirst}>▲</button>
          <button className="action-btn move" onClick={onMoveDown} disabled={isLast}>▼</button>
          <button className="action-btn delete" onClick={onDelete}>×</button>
        </div>
      </div>
      
      {item.type === "submenu" && item.children && item.children.length > 0 && (
        <div style={{ marginTop: '0.75rem', marginBottom: '1.5rem' }}>
          {item.children.map((child, idx) => (
             <MenuItemRow
                key={child.id}
                item={child}
                index={idx}
                onUpdate={(u) => onUpdate(u, child.id)}
                onDelete={() => onDelete(child.id)}
                onMoveUp={() => onMoveUp(child.id, -1)}
                onMoveDown={() => onMoveUp(child.id, 1)}
                isFirst={idx === 0}
                isLast={idx === item.children.length - 1}
                depth={depth + 1}
                onAddChild={onAddChild}
             />
          ))}
        </div>
      )}
    </div>
  );
}

function MenuPreview({ items, depth = 0 }) {
  return (
    <div className="fake-menu" style={{ width: depth === 0 ? '100%' : 'calc(100% - 16px)', marginLeft: depth > 0 ? 16 : 0 }}>
      {items.map((item, i) => {
        if (item.type === "separator") {
          return <div key={item.id} style={{ height: 1, background: "rgba(255,255,255,0.1)", margin: "4px 0" }} />;
        }
        return (
          <div key={item.id} style={{ display: 'flex', flexDirection: 'column' }}>
            <div
              style={{
                display: 'flex', alignItems: 'center', gap: '12px',
                padding: "6px 24px 6px 16px",
                color: "#e2e8f0",
                fontSize: "13px",
                cursor: "default",
                justifyContent: 'space-between'
              }}
              onMouseEnter={e => {
                e.currentTarget.style.background = "#fff3";
                e.currentTarget.style.color = "#fff";
              }}
              onMouseLeave={e => {
                e.currentTarget.style.background = "transparent";
                e.currentTarget.style.color = "#e2e8f0";
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                <span style={{ width: 16, height: 16, display: "flex", alignItems: "center", justifyContent: "center", opacity: 0.7 }}>
                  {TYPE_ICONS[item.type]}
                </span>
                <span>{item.name || "Untitled"}</span>
              </div>
              {item.type === "submenu" && (
                 <span style={{ width: 14, height: 14, display: 'flex', alignItems: 'center', justifyContent: 'center', opacity: 0.5 }}>
                   <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                     <polyline points="9 18 15 12 9 6" />
                   </svg>
                 </span>
              )}
            </div>
            {item.type === "submenu" && item.children && item.children.length > 0 && (
               <div style={{ position: 'relative', marginTop: '2px', paddingBottom: '4px' }}>
                  <MenuPreview items={item.children} depth={depth + 1} />
               </div>
            )}
          </div>
        );
      })}
      {items.length === 0 && depth === 0 && (
        <div style={{ padding: "16px", color: "#64748b", fontSize: "12px", fontStyle: "italic", textAlign: "center" }}>
          Add items to see preview
        </div>
      )}
    </div>
  );
}

function CodePreview({ code }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div style={{ position: "relative" }}>
      <button onClick={handleCopy} style={{
        position: "absolute", top: 12, right: 12, padding: "6px 12px",
        background: copied ? "rgba(34,197,94,0.15)" : "rgba(255,255,255,0.05)",
        border: "1px solid " + (copied ? "rgba(34,197,94,0.3)" : "rgba(255,255,255,0.1)"),
        borderRadius: 6, color: copied ? "#4ade80" : "#94a3b8", fontSize: '0.75rem', cursor: "pointer",
        fontFamily: "'JetBrains Mono', monospace", transition: 'all 0.2s', zIndex: 10
      }}>
        {copied ? "✓ Copied" : "Copy"}
      </button>
      <pre className="code-container">
        {code.split("\n").map((line, i) => {
          let color = "#9ca3af";
          if (line.startsWith(";")) color = "#4ade80"; // comments
          else if (line.includes("::")) color = "#f59e0b"; // hotkey
          else if (line.startsWith("Menu,")) color = "#60a5fa"; // commands
          else if (line.match(/^(if|else if|return)/)) color = "#c084fc"; // logic
          else if (line.startsWith("#") || line.startsWith("Set")) color = "#f472b6"; // directives
          else if (line.includes("Run,")) color = "#34d399"; // execution
          return <span key={i} style={{ color }}>{line}{"\n"}</span>;
        })}
      </pre>
    </div>
  );
}

export default function AHKMenuDesigner() {
  const [items, setItems] = useState(DEFAULT_ITEMS);
  const [hotkey, setHotkey] = useState("#z");
  const [customHotkey, setCustomHotkey] = useState("");
  const [menuTitle] = useState("QuickMenu");
  const [nextId, setNextId] = useState(3);
  const [activeTab, setActiveTab] = useState("preview");

  const addItem = (parentId, type = "app") => {
    const newItem = { id: nextId, name: "", icon: "", target: "", type, children: type === "submenu" ? [] : undefined };
    setItems(addItemRec(items, parentId, newItem));
    setNextId(nextId + 1);
  };

  const updateItem = (updated, childIdOverride) => {
    // Determine the ID to update. If a child called this via MenuItemRow directly, it will supply the ID in second argument 
    // Wait, the MenuItemRow passes (u) => onUpdate(u) or (u) => onUpdate(u, child.id).
    // Let's just use updated.id since it's cleaner.
    if (updated && updated.id) {
       setItems(updateItemRec(items, updated.id, updated));
    }
  };
  
  const deleteItem = (id) => setItems(deleteItemRec(items, id));

  const moveItem = (id, dir) => {
    setItems(moveItemRec(items, id, dir));
  };

  const code = generateAHK(items, hotkey, customHotkey, menuTitle);

  const downloadScript = () => {
    const blob = new Blob([code], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "ContextMenu.ahk";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <div className="bg-blobs">
        <div className="blob blob-1"></div>
        <div className="blob blob-2"></div>
      </div>
      
      <div className="app-container">
        {/* Header */}
        <div className="glass-panel header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
            <div className="header-logo-icon">⌥</div>
            <div>
              <h1 style={{ margin: 0, fontSize: '1.25rem', fontWeight: 600, letterSpacing: '-0.02em', color: 'var(--text-main)' }}>
                AHK Menu Designer
              </h1>
              <p style={{ margin: 0, fontSize: '0.7rem', color: 'var(--text-muted)', letterSpacing: '0.04em', fontWeight: 500, marginTop: '2px' }}>
                DESIGN · PREVIEW · EXPORT
              </p>
            </div>
          </div>
          <button className="btn-primary" onClick={downloadScript}>
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
              <polyline points="7 10 12 15 17 10"></polyline>
              <line x1="12" y1="15" x2="12" y2="3"></line>
            </svg>
            Download .ahk
          </button>
        </div>

        {/* Main Content */}
        <div className="main-content">
          {/* Left Panel - Editor */}
          <div className="glass-panel col-left">
            {/* Hotkey Config */}
            <div className="section-header" style={{ display: 'flex', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' }}>
              <span className="label-caps">Trigger Hotkey</span>
              <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                {HOTKEY_OPTIONS.map((opt) => (
                  <button
                    key={opt.value}
                    className={`hotkey-btn ${hotkey === opt.value ? 'active' : ''}`}
                    onClick={() => setHotkey(opt.value)}
                  >
                    {opt.display}
                  </button>
                ))}
              </div>
              {hotkey === "custom" && (
                <input
                  className="input-field"
                  value={customHotkey}
                  onChange={(e) => setCustomHotkey(e.target.value)}
                  placeholder="e.g. ^!m"
                  style={{ width: '120px', border: '1px solid var(--accent-primary)', color: 'var(--accent-primary)' }}
                />
              )}
            </div>

            {/* Menu Items List */}
            <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column' }}>
              <div style={{ padding: '1rem 1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <span className="label-caps">Menu Items ({items.length})</span>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button className="add-btn" onClick={() => addItem(null, "app")}>+ App</button>
                  <button className="add-btn" onClick={() => addItem(null, "folder")}>+ Folder</button>
                  <button className="add-btn" onClick={() => addItem(null, "url")}>+ URL</button>
                  <button className="add-btn" onClick={() => addItem(null, "submenu")} style={{ background: 'rgba(56, 189, 248, 0.15)', color: '#38bdf8', borderColor: 'rgba(56, 189, 248, 0.3)' }}>+ Submenu</button>
                  <button className="add-btn muted" onClick={() => addItem(null, "separator")}>— Sep</button>
                </div>
              </div>

              <div style={{ flex: 1 }}>
                {items.map((item, idx) => (
                  <div key={item.id} style={{ animation: 'fadeIn 0.3s ease-out' }}>
                    <MenuItemRow
                      item={item}
                      index={idx}
                      onUpdate={(u) => updateItem(u)}
                      onDelete={() => deleteItem(item.id)}
                      onMoveUp={(idOverrides, dir) => typeof idOverrides === 'number' ? moveItem(idOverrides, dir) : moveItem(item.id, -1)}
                      onMoveDown={(idOverrides, dir) => typeof idOverrides === 'number' ? moveItem(idOverrides, dir) : moveItem(item.id, 1)}
                      isFirst={idx === 0}
                      isLast={idx === items.length - 1}
                      onAddChild={addItem}
                    />
                  </div>
                ))}

                {items.length === 0 && (
                  <div style={{ padding: '3rem 2rem', textAlign: 'center', color: 'var(--text-muted)' }}>
                    <p style={{ margin: 0, fontSize: '0.9rem', fontWeight: 500 }}>No menu items yet</p>
                    <p style={{ margin: '0.5rem 0 0', fontSize: '0.75rem', opacity: 0.8 }}>Add apps, folders, or URLs above to start building</p>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Right Panel - Preview/Code */}
          <div className="glass-panel col-right">
            <div className="tabs">
              <button className={`tab-btn ${activeTab === 'preview' ? 'active' : ''}`} onClick={() => setActiveTab('preview')}>
                ⬡ Live Preview
              </button>
              <button className={`tab-btn ${activeTab === 'code' ? 'active' : ''}`} onClick={() => setActiveTab('code')}>
                {'{ }'} AHK Code
              </button>
            </div>

            <div className="preview-content">
              {activeTab === "preview" ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
                  <div>
                    <h3 className="label-caps" style={{ margin: '0 0 0.5rem 0' }}>Simulated UI</h3>
                    <p style={{ margin: 0, fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                      Press <span style={{ color: 'var(--accent-primary)', fontFamily: '"JetBrains Mono", monospace' }}>
                        {hotkey === "custom" ? (customHotkey || "...") : HOTKEY_OPTIONS.find(h => h.value === hotkey)?.display}
                      </span> to trigger
                    </p>
                    <div style={{ marginTop: '1.5rem', display: 'flex', justifyContent: 'center', padding: '2rem 0' }}>
                      <MenuPreview items={items} />
                    </div>
                  </div>

                  <div style={{ padding: '1.25rem', borderRadius: '12px', background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.15)' }}>
                    <h4 style={{ margin: '0 0 0.5rem 0', fontSize: '0.85rem', color: 'var(--accent-primary)' }}>Quick Guide</h4>
                    <ol style={{ margin: 0, paddingLeft: '1.25rem', fontSize: '0.8rem', color: 'var(--text-muted)', lineHeight: 1.7 }}>
                      <li>Build your context menu using the editor on the left.</li>
                      <li>Customize your shortcut trigger.</li>
                      <li>Export the script via the <strong style={{ color: 'var(--text-main)' }}>Download .ahk</strong> button.</li>
                      <li>Run the resulting file using AutoHotkey v1.1.</li>
                    </ol>
                  </div>
                </div>
              ) : (
                <CodePreview code={code} />
              )}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
